.\" Cati manual page
.\" This file is part of cati project
.\" Copyright 2020 parsa shahmaleki <parsampsh@gmail.com>

.TH cati 1 "6 December 2020" "Cati 0.1-dev" "Cati Manual"

.SH NAME
cati - Package Manager

.SH SYNOPSIS
.B cati
{
help [?
.I command-name
] |
pkg [ show 
.I pkg1.cati
| build
.I pkg1-dir
| install 
.I pkg1.cati
]
| list |
remove
.I pkg1 pkg2
| show
.I pkg1 pkg2=<version>
| state [ --abort, --complete, -y|--yes ]
| query
.I "pkgx >= 4.5"
| search
.I "word"
| files
.I pkg1 pkg2
 | finfo
.I /path/to/file
| rdepends
.I pkg1 pkg2
 | forget
.I pkg1 pkg2=<version>
| check |
repo [-a|--add, -e|--edit, --scan] |
update |
autoremove |
clear-cache |
download 
.I pkg1 --output=<out.cati>
| install
.I pkg1 pkg2
| upgrade |
full-upgrade}
{--version, --help, -v|--verbose, -q|--quiet, --no-ansi}

.SH DESCRIPTION
.B cati
is a package manager for UNIX systems. cati can install/remove/list and manage packages on system.
also cati can load packages lists from repositories(local file repositories and http server repositories).
cati is very simple and easy to use and also is powerful.

.B help
shows this help

.B pkg
work with .cati packages

.B list
shows list of packages

.B remove
remove packages

.B show
shows details of packages

.B state
manage transactions state

.B query
checks a package query

.B search
search between packages by name and description

.B files
shows files list of packages

.B finfo
shows info about an file

.B rdepends
shows reverse depends list of packages

.B forget
forgets packages from packages list

.B check
checks system health and security

.B repo
manage repositories

.B update
updates list of available packages from repositories

.B autoremove
remove unused automaticaly installed packages

.B clear-cache
clears cache files

.B download
download packages

.B install
install packages

.B upgrade
upgrade all of packages

.B full-upgrade
update, upgrade and autoremove

.SH DIAGNOSTICS
cati returns zero exit code when process is successful and returns exit code 1 when there is an error.

.SH AUTHOR
.B parsa shahmaleki <parsampsh@gmail.com>
