name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        cat requirements.txt | grep -v 'pkg-resources==0.0.0' > tmp-requirements.txt
        pip3 install -r tmp-requirements.txt
    - name: Run tests
      run: make all

    name: Python ${{ matrix.python }}

  linux_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        cat requirements.txt | grep -v 'pkg-resources==0.0.0' > tmp-requirements.txt
        pip3 install -r tmp-requirements.txt
    - name: Build
      run: |
        make all
        make
        sudo ./dist/cati

    name: Build Python ${{ matrix.python }}

  dockerfile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        docker_nightly_version: snapshot-20201008
    - name: Build Image
      run: |
        docker build -t cati .

    name: Dockerfile
