name: tests

on:
  push:
    paths-ignore:
    - 'doc/**'
  pull_request:
    paths-ignore:
    - 'doc/**'

jobs:
  unix_tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Run tests
      run: make all
    - name: Test Build
      run: |
        make
        sudo ./dist/cati

    name: ${{ matrix.os }} with python ${{ matrix.python }}
